defmodule Mix.Tasks.Frontend.Build.Js.Exthelp do
  use MBU.BuildTask, auto_path: false, create_out_path: false
  import CodeStats.FrontendConfs

  @shortdoc "Build the Babel external helpers that are needed by the frontend code"

  def out_file(), do: Path.join([js_path(), "common", "babel-external-helpers.js"])

  task _ do
    bin = node_bin("babel-external-helpers")

    {code, 0} = System.cmd(bin, ["-t", "global"])

    code =
      """
      // This file is autogenerated by the task frontend.build.js.exthelp, do not modify this file
      // by hand. This file is gitignored.
      """ <> code

    File.write!(out_file(), code)
  end
end
